# Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/itq_docs
spring.datasource.url=jdbc:postgresql://localhost:5432/itq_docs
spring.datasource.username=itq_user
spring.datasource.password=itq_password
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.liquibase.enabled=false

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


logging.level.org.springframework.jdbc.datasource=INFO
logging.level.com.zaxxer.hikari=INFO
logging.level.org.postgresql=INFO

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Server Configuration
server.port=8080

#Worker configuration
worker.batch-size=5
worker.submit-cron=0 */5 * * * *
worker.approve-cron=0 */5 * * * *

#Logger configuration
logging.file.name=../logs/document-service.log
logging.level.com.itq.document=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB