# Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/itq_docs
spring.datasource.url=jdbc:postgresql://localhost:5432/itq_docs
spring.datasource.username=itq_user
spring.datasource.password=itq_password
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.liquibase.enabled=false

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.postgresql=DEBUG

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Server Configuration
server.port=8080
